name: refresh_circular_progression
description: This is a package providing you with a customized circular progress bar
version: 0.0.2
homepage: 'https://github.com/zetsu01/flutter_custom_circular_progress_indicator'
environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
